# Generated by Django 2.1.7 on 2019-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='peri@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='nopassword', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
