# Generated by Django 2.1.7 on 2019-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_auto_20190322_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
