# Generated by Django 2.1.7 on 2019-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_auto_20190322_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/Images/'),
        ),
    ]
