# Generated by Django 2.1.7 on 2019-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0004_user_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='Images/'),
        ),
    ]
