# Generated by Django 2.1.7 on 2019-03-27 22:40

from django.db import migrations, models
import lol.models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0007_auto_20190327_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField(verbose_name='release date')),
                ('genre', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to=lol.models.gamespic)),
            ],
        ),
    ]
