# Generated by Django 2.1.7 on 2019-03-27 23:31

from django.db import migrations, models
import lol.models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0008_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to=lol.models.function),
        ),
    ]
