# Generated by Django 2.1.7 on 2019-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0009_auto_20190327_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
