# Generated by Django 2.1.7 on 2019-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0011_hyperatio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperatio',
            name='dislike_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hyperatio',
            name='like_votes',
            field=models.IntegerField(default=0),
        ),
    ]
