# Generated by Django 2.1.7 on 2019-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0012_auto_20190329_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
    ]
